import com.hsbc.ruleengine.entity.FileModel;

global com.hsbc.ruleengine.service.PaymentService paymentService;

rule "PDF"

when
    fileModule : FileModel(fileType == "pdf");
then
    paymentService.processPDFFile(fileModule);
end


rule "TXT"

when
    fileModule : FileModel(fileType == "txt");
then
    paymentService.processTXTFile(fileModule);
end



rule "CSV"

when
    fileModel : FileModel(fileType == "csv");
then
    paymentService.processCSVFile(fileModel);
end